apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-genre-api
spec:
  replicas: {{ .Values.genreApi.replicaCount }}
  selector:
    matchLabels:
      app: genre-api
  template:
    metadata:
      labels:
        app: genre-api
    spec:
      containers:
        - name: genre-api
          image: "{{ .Values.genreApi.image.repository }}:{{ .Values.genreApi.image.tag }}"
          ports:
            - containerPort: {{ .Values.genreApi.port }}
          env:
            - name: PORT
              value: "{{ .Values.genreApi.port }}"
            - name: LOG_LEVEL
              value: {{ .Values.global.logLevel }}
            - name: MONGO_SERVICE_URL
              value: {{ .Values.mongo.url }}
---
apiVersion: v1
kind: Service
metadata:
  name: genre-api
spec:
  selector:
    app: genre-api
  ports:
    - protocol: TCP
      port: {{ .Values.genreApi.port }}
      targetPort: {{ .Values.genreApi.port }}
