apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-transcoder
spec:
  replicas: {{ .Values.transcoder.replicaCount }}
  selector:
    matchLabels:
      app: transcoder
  template:
    metadata:
      labels:
        app: transcoder
    spec:
      containers:
        - name: transcoder
          image: "{{ .Values.transcoder.image.repository }}:{{ .Values.transcoder.image.tag }}"
          ports:
            - containerPort: {{ .Values.transcoder.port }}
          env:
            - name: PORT
              value: "{{ .Values.transcoder.port }}"
            - name: LOG_LEVEL
              value: {{ .Values.global.logLevel }}
            - name: RABBITMQ_URL
              value: {{ .Values.rabbitmq.url }}
            - name: ENCODING_QUEUE
              value: {{ .Values.transcoder.encodingQueue }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.global.s3BucketName }}
            - name: AWS_REGION
              value: {{ .Values.minio.region }}
            - name: S3_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.minio.accessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.minio.secretKey }}
---
apiVersion: v1
kind: Service
metadata:
  name: transcoder
spec:
  selector:
    app: transcoder
  ports:
    - protocol: TCP
      port: {{ .Values.transcoder.port }}
      targetPort: {{ .Values.transcoder.port }}
